// IMPORTANT! File generated by /home/jozsef/projects/hyperWiki/install.sh
/* eslint-disable */
const config = {
	ENDPOINT_CHILDREN: "topic/children/",
	ENDPOINT_PAGE: "page/",
	ENDPOINT_SEARCH: "info/search",
	HOST: "localhost",
	ORIGIN: "http://localhost:8020/",
	PORT: "8020",
	DEBUG_LEVEL:"error",
	URL_CHILDREN: "http://localhost:8020/topic/children/",
	URL_PAGE: "http://localhost:8020/page/",
	URL_SEARCH: "http://localhost:8020/info/search",
	URL_USER_ADD: "http://localhost:8010/user/add/",
	URL_USER_AUTHINTICATE: "http://localhost:8010/user/authinticate/",
	URL_USER_GET: "http://localhost:8010/user/get/",
	URL_USER_LOGIN: "http://localhost:8010/user/login/",
	URL_USER_RESET: "http://localhost:8010/user/reset/password/",
	URL_USER_UPDATE: "http://localhost:8010/user/update/",
	URL_USER_UPDATE_PASSWORD: "http://localhost:8010/user/update/password/",
	WEB_SOCKET_URL: "ws://localhost:8030/topic/"
};

exports.config = config;
